name: CI

on:
  pull_request:
    branches:
      - main

env:
  dfx_version: 0.31.0-beta.1

permissions:
  contents: read

jobs:
  fractal_sortition_oc_bot_backend_test:
    name: Fractal Sortition OC bot backend - Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: caffeinelabs/setup-mops@v1

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: ${{ env.dfx_version }}

      - name: Confirm dfx version
        run: dfx --version

      - name: Make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Show mops version
        run: mops -v

      - name: Run mops test
        run: mops test